server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Rất quan trọng: Giúp React Router không bị lỗi 404 khi F5
        try_files $uri $uri/ /index.html; 
    }
}